name         'puppetlabs-ironic'
version      '0.0.1'
author       'StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Ironic'
description  'Installs and configures OpenStack Ironic (Bare metal).'
project_page 'https://launchpad.net/puppet-ironic'
source       'https://github.com/stackforge/puppet-ironic'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=2.0.0 <3.0.0'
dependency 'puppetlabs/stdlib', '>=2.3.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
